[package]
name = "invaders"
version = "0.1.0"
authors = ["Keys <70819367+keys-i@users.noreply.github.com>"]
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rusty_audio = "1.4.1"
rusty_time = "0.11.0"
